default: &default
  store_options:
    max_age: <%= 1.week.to_i %>
    max_size: <%= 256.megabytes %>

development:
  <<: *default

test:
  <<: *default
  store_options:
    max_age: 60

production:
  <<: *default
  database: cache
  store_options:
    max_age: <%= 1.week.to_i %>