default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  username: yusuf
  password: yusuf123
  database: taskflow_development

test:
  <<: *default
  host: localhost
  username: yusuf
  password: yusuf123
  database: taskflow_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
